### ISSUE TITLE
Feature request, adding keybinds?

### ISSUE THREAD

**Issue by errorsallthethings** [fxys/Super-Secret-Settings#1]
I have a feature request to be able to cycle through the super secret settings shaders. 

Thanks for putting this together, I know it's a silly thing but it does have it's uses. Working great on Fabric 1.18.1 + Iris + Soduim. Just wish I could cycle through them via keybind instead of having to click on the button each time. 

Either way thanks again for making this mod!

**Comment by fxys** [comment]
Keybinds have been added in the latest version + other features (:

**Comment by errorsallthethings** [comment]
@fxys you are my favorite person today! I'll download the latest update and play with it. Thank you! :D
