### ISSUE TITLE
[Feature Request] Permenant Shader

### ISSUE THREAD

**Issue by Thanos1716** [fxys/Super-Secret-Settings#4]
Hey,
I was thinking it could be cool if there was a resourcepack file that allowed me to apply a shader at all times (or at least when no other one is applied)
for example in assets/supersecretsettings/shaders/default.fs or something, just so I could use it in general gameplay without going into a menu whenever the game restarts
Thanks for such a nostalgic mod :)

**Comment by fxys** [comment]
I could create a shaderpack that can be loaded with OptiFine/IrisShaders. Is this what you mean?

**Comment by Thanos1716** [comment]
I was thinking something more simple, just a vanilla post processing fragment shader that is tweakable by a resourcepack, like super secret settings, but always enabled; super secret settings disables whenever you restart the game, but you can edit the sss shaders by making a resourcepack.
Although an OF/Iris shader would accomplish a similar thing, the down side of that is you can't use another OF/Iris shader at the same time.
Personally this little addition would add a lot of value to the mod for me :)

**Comment by fxys** [comment]
I see. I can implement a config file to save the name of the current shader so that when the game is restarted the shader can be automatically enabled.

**Comment by fxys** [comment]
This version of the mod saves the name of the current shader and reapplies it when you restart the game.

[https://www.mediafire.com/file/3fbnvheb10rana3/sss-1.20-1.2.0.jar/file](https://www.mediafire.com/file/3fbnvheb10rana3/sss-1.20-1.2.0.jar/file)

**Comment by Thanos1716** [comment]
Yes that is perfect, thank you!
